# Generated by Django 5.1.15 on 2026-08-24 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimientos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_uri', models.CharField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('scopes', models.TextField(blank=True, default='https://www.googleapis.com/auth/gmail.readonly')),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('email_cuenta', models.EmailField(blank=True, max_length=254)),
                ('conectado', models.BooleanField(default=False)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion Gmail',
                'verbose_name_plural': 'Configuracion Gmail',
            },
        ),
        migrations.CreateModel(
            name='EmailProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=200, unique=True)),
                ('thread_id', models.CharField(blank=True, max_length=200)),
                ('remitente', models.CharField(blank=True, max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=500)),
                ('fecha_correo', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('IGNORADO', 'Ignorado')], default='EXITOSO', max_length=15)),
                ('datos_extraidos', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_origen', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'Email procesado',
                'verbose_name_plural': 'Emails procesados',
                'ordering': ['-procesado_en'],
            },
        ),
    ]
