# Generated by Django 5.1.15 on 2026-08-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='movimientos.movimiento'),
        ),
    ]
