# Generated by Django 5.1.15 on 2026-08-24 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo inicial con el que arranca el sistema.', max_digits=18)),
                ('nombre_cuenta', models.CharField(default='Cuenta principal', max_length=120)),
                ('banco', models.CharField(default='Bancolombia', max_length=80)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del sistema',
                'verbose_name_plural': 'Configuracion del sistema',
            },
        ),
    ]
