# Generated by Django 5.1.15 on 2026-08-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('banco', models.CharField(default='Bancolombia', max_length=80)),
                ('numero', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('saldo_banco', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_sistema', models.DecimalField(decimal_places=2, max_digits=18)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='conciliacion.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Conciliacion',
                'verbose_name_plural': 'Conciliaciones',
            },
        ),
    ]
