# Generated by Django 5.1.15 on 2026-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#1e3a8a', help_text='Color en formato HEX para las graficas.', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo'), name='categoria_nombre_tipo_unico')],
            },
        ),
    ]
