# Generated by Django 5.1.15 on 2026-08-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('texto_ocr', models.TextField(blank=True, help_text='Texto crudo extraido por OCR.')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('subcategoria', models.CharField(blank=True, max_length=120)),
                ('banco', models.CharField(blank=True, default='Bancolombia', max_length=80)),
                ('cuenta', models.CharField(blank=True, max_length=80)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=120)),
                ('tercero', models.CharField(blank=True, max_length=200)),
                ('saldo_despues', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('origen', models.CharField(choices=[('EMAIL', 'Correo electronico'), ('MANUAL', 'Registro manual'), ('OCR', 'OCR comprobante'), ('IMPORTACION_EXCEL', 'Importacion Excel'), ('OTRO', 'Otro')], default='MANUAL', max_length=20)),
                ('estado_conciliacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=15)),
                ('email_message_id', models.CharField(blank=True, help_text='ID del correo Gmail cuando el origen es EMAIL.', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-hora', '-id'],
            },
        ),
    ]
