# Generated by Django 5.1.15 on 2026-08-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_destino',
            field=models.CharField(blank=True, help_text='Cuenta destino (para transferencias)', max_length=80),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nombre_destinatario',
            field=models.CharField(blank=True, help_text='Nombre del destinatario (para transferencias)', max_length=200),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.CharField(blank=True, help_text='Cuenta origen', max_length=80),
        ),
    ]
